# Required configuration
source: source
destination: public
code_dir: downloads/code
port: 4000

url: http://yoursite.com
title: My Octopress Blog
permalink: /blog/:year/:month/:day/:title
subtitle: A blogging framework for hackers.
author: Your Name
subscribe_rss: /atom.xml
subscribe_email:

markdown: rdiscount
pygments: true
#posts_per_page: 10
paginate: 5
recent_posts: 5
category_dir: category
simple_search: http://google.com/search

# Optional configurations

# For RSS Feed
email:

# Twitter
twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:

# Google Analytics
google_analytics_tracking_id:
