# Required configuration
source: source
destination: public
plugins: plugins
code_dir: downloads/code
port: 4000

url: http://yoursite.com
title: My Octopress Blog
permalink: /blog/:year/:month/:day/:title
subtitle: A blogging framework for hackers.
author: Your Name

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:

markdown: rdiscount
pygments: true
paginate: 10
recent_posts: 5
category_dir: blog/categories
simple_search: http://google.com/search

# Optional configurations

# RSS feeds can list your email address if you like
email:

# Twitter
twitter_user: imathis
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google Plus
google_plus_one: true
google_plus_one_size: medium

# Pinboard
pinboard_user: imathis
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: octopress

# Google Analytics
google_analytics_tracking_id:
